#!/usr/bin/env bash
# Render the app icon to AppleMusicMCP.icns. Regenerate after editing make-icon.swift.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
swiftc -O -o /tmp/amcp-make-icon make-icon.swift
/tmp/amcp-make-icon AppleMusicMCP.iconset
iconutil -c icns AppleMusicMCP.iconset -o AppleMusicMCP.icns
rm -rf AppleMusicMCP.iconset /tmp/amcp-make-icon
echo "wrote $(pwd)/AppleMusicMCP.icns ($(du -h AppleMusicMCP.icns | cut -f1))"

# A small PNG of the same icon, embedded as base64 so the MCP server can hand
# its icon to clients that show one. Generated, not committed as a binary blob
# nobody can review: regenerate with this script after editing make-icon.swift.
sips -s format png --resampleWidth 128 AppleMusicMCP.icns --out /tmp/amcp-icon-128.png >/dev/null
python3 - <<'PY'
import base64, pathlib, textwrap
data = base64.b64encode(pathlib.Path("/tmp/amcp-icon-128.png").read_bytes()).decode()
out = pathlib.Path(__file__).resolve().parents[2] / "src" / "applemusic_mcp" / "icon.py"
out.write_text(
    '"""The app icon, for clients that display one next to a server.\n\n'
    "Generated by tools/icon/build.sh from AppleMusicMCP.icns -- do not edit by\n"
    "hand. Embedded as base64 rather than shipped as a data file so it survives\n"
    "any packaging arrangement, and as source rather than a committed binary so\n"
    'a reviewer can regenerate it and compare.\n"""\n\n'
    "MIME_TYPE = \"image/png\"\nSIZE = \"128x128\"\n\nPNG_BASE64 = (\n"
    + "".join(f'    "{line}"\n' for line in textwrap.wrap(data, 96))
    + ")\n\nDATA_URI = f\"data:{MIME_TYPE};base64,{PNG_BASE64}\"\n",
    encoding="utf-8",
)
print(f"wrote {out} ({len(data)} base64 chars)")
PY
rm -f /tmp/amcp-icon-128.png
